name: CI/CD for Node.js App

on:
  push:
    branches:
      - main    # Run when code is pushed to main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1 – Check out code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2 – Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3 – Build + Push image to Docker Hub
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: paulhu1818/nodejs-container-app:latest


  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push     # Run after build succeeds
    steps:
      - name: Deploy to Server
        run: |
          echo "Deploying container to production..."
          # Example:
          # ssh user@your-server "docker pull paulhu1818/nodejs-container-app:latest && docker run -d -p 80:3000 <docker-username>/<repo-name>:latest"
